### ISSUE TITLE
Alternative alignment and win condition!

### ISSUE THREAD

**Issue by Lunethia** [SilverLous/ttt2-role-cupid#1]
Alternatively to the Cupid being and Innocent, make them a Neutral team!
They can still create two lovers!
They win with their lovers and alone!
The Lovers know who cupid is/Dont know who cupid is, do it as you want.
The Lovers only win with each other and cupid and form a new team -- always!

**Comment by SilverLous** [comment]
Functionality added!

**Comment by Lunethia** [comment]
Hey! Since this isn't closed yet, a follow up!
I've tested the functionality of this addition now, and it seems, that the Cupid is bound to both lovers (taking their damage) is that intendet?
![image](https://user-images.githubusercontent.com/52287610/81458899-431ba680-919d-11ea-90c0-69b3cb85373f.png)
A screenshot of my Cvar setup.
Is the Cupid intendet to take damage there? All three die if one of them would die. I think, since the cupid isnt a lover, he shouldnt take the shared damage, right?
If the Lovers die, i think the Cupid shouldnt? 
One could talk about the Cupid being unable to win then. Hmm.

**Comment by SilverLous** [comment]
Yeah now that i think about it it doesnt really make sense to share damage Ill remove it now

**Comment by SilverLous** [comment]
Damage split disabled if Cupid is not in love
