### ISSUE TITLE
Lover bugged

### ISSUE THREAD

**Issue by guillermomolla** [SilverLous/ttt2-role-cupid#2]
Sometimes when you make 2 people in love, they see each other in love, but the cupid also see him  self in love with one of them (not both)
Also there is so many times where it just wont work.

**Comment by PROFI5** [comment]
theres a bug when the cupid Can make himself in love and when he shoots someone with the cupid bow the cupid bow just goes away im sorry if i am misunderstooded

**Comment by SilverLous** [comment]
I think i fixed both bugs a long time ago
