### ISSUE TITLE
ttt_cupid_old_weapon doesn't work

### ISSUE THREAD

**Issue by TaintedEnergy** [SilverLous/ttt2-role-cupid#5]
[[TTT2] Cupid [ROLE]] gamemodes/terrortown/entities/weapons/weapon_ttt2_cupidsbow/shared.lua:102: attempt to index field 'lovedOnesArmor' (a nil value)
  1. DoClick - gamemodes/terrortown/entities/weapons/weapon_ttt2_cupidsbow/shared.lua:102
   2. unknown - lua/vgui/dlabel.lua:237

Error appears when attempting to use old weapon and doesn't set lovers.

**Comment by SilverLous** [comment]
Should be fixed now.
